# Generated by Django 2.1.2 on 2018-10-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181031_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
