# Generated by Django 2.1.2 on 2018-10-29 20:01

from django.db import migrations


def create_default_image(apps, schema_editor):
    Image = apps.get_model('images', 'image')
    Image.objects.create(
        title='default',
        value='images/default.jpg'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(

        )
    ]
